src/StreamingClient.php

Fixed `PHP Warning:  fread(): 294 is not a valid stream resource in .../react/stream/src/Stream.php on line 127`
Call Stream::resume in https://github.com/reactphp/stream/blob/master/src/Stream.php#L40
Perhaps this problem, Read Stream Listener is not successfully deleted when you close the connection, warning came out after a while.
Code to strictly reproduce is difficult, but it was caused by my production.
This pull request, because the first time that for me, there may be a problem with the manners, but please forgive me. and i'm afraid my expressions may be rude or hard to read, because I'm not so good at English.

Remove unneeded resume() call

---

composer.json
src/Factory.php
tests/FactoryTest.php

This is done in preparation for a follow-up PR that addresses #50

Update SocketClient to latest version

---

README.md
composer.json
src/ConnectionUpcaster.php
src/ConnectorUpcaster.php
src/Factory.php
src/StreamingClient.php
tests/FactoryTest.php
tests/FunctionalTest.php

If you need custom connector settings (DNS resolution, TLS parameters, timeouts,
proxy servers etc.), you can explicitly pass a custom instance of the
[`ConnectorInterface`](https://github.com/reactphp/socket#connectorinterface):
```php
$connector = new \React\Socket\Connector($loop, array(
'dns' => '127.0.0.1',
'tcp' => array(
'bindto' => '192.168.10.1:0'
),
'tls' => array(
'verify_peer' => false,
'verify_peer_name' => false
)
));
$factory = new Factory($loop, $connector);
```
Builds on top of #58
Refs #50
Heavily inspired by https://github.com/clue/php-buzz-react/pull/76

Factory accepts Connector from Socket and deprecate legacy SocketClient

---

README.md
src/Factory.php
tests/FactoryTest.php

This project now supports standard `redis://` and `rediss://` URI schemes:
```php
$factory->createClient('redis://:secret@localhost:6379/4');
$factory->createClient('redis://localhost:6379?password=secret&db=4');
```
See also https://www.iana.org/assignments/uri-schemes/prov/redis and https://www.iana.org/assignments/uri-schemes/prov/rediss
Resolves / closes #40 
Supersedes / closes #42

Support redis[s]:// URI scheme and deprecate legacy URIs

---

README.md
examples/cli.php
src/Client.php
src/StreamingClient.php
tests/StreamingClientTest.php

The `data` event is underdocumented for the most part and has attracted some low quality code in the past. It used to be more of a poor attempt to make the `Client` behave like a `ReadableStreamInterface` which doesn't make much sense for the rest of the interface anyway.
As such, this PR simply removes the `data` event, which makes the interface more consistent. Removing unneeded events also has a noticeable effect on performance.

Remove uneeded data event for performance and consistency reasons

---

src/Client.php
src/StreamingClient.php
tests/FunctionalTest.php
tests/StreamingClientTest.php

The `isBusy()` method is underdocumented (not even documented in the README) and has attracted some low quality code in the past.
This PR simply removes this method, which reduces surface of the interface and makes the remaining interface more consistent.

Remove underdocumented isBusy() method

---

composer.json
tests/FunctionalTest.php
tests/StreamingClientTest.php

Builds on top of #59 and #61 
Resolves / closes #50
Supersedes / closes #51

Forward compatibility with upcoming Socket v1.0 and v0.8 and EventLoop v1.0 and Evenement v3

---

composer.json
src/Factory.php
tests/FactoryTest.php

The underlying `Connector` now honors the hosts file on all platforms by default. This means that you can now send requests to `localhost` etc..
Resolves / closes #32
Refs reactphp/socket#112
Originally from https://github.com/reactphp/http-client/pull/108

Update Socket dependency to support hosts file on all platforms

---

composer.json
phpunit.xml.dist
tests/FactoryTest.php
tests/FunctionalTest.php
tests/StreamingClientTest.php
tests/TestCase.php
tests/bootstrap.php

Improve test suite structure and add forward compatibility with PHPUnit 7 and PHPUnit 6

---

README.md
composer.json
src/Factory.php
tests/FactoryTest.php

Builds on top of https://github.com/reactphp/socket/pull/170 and
https://github.com/reactphp/socket/pull/177
Refs https://github.com/friends-of-reactphp/mysql/pull/84 and
https://github.com/clue/reactphp-buzz/pull/110

Support cancellation of pending connection attempts

---

README.md
composer.json
src/Factory.php
tests/FactoryTest.php

Resolves #10 
Builds on top of #85 
Refs https://github.com/friends-of-reactphp/mysql/pull/86

Support connection timeouts

---

examples/subscribe.php
src/LazyClient.php
tests/LazyClientTest.php

Fix closing lazy connection from within rejection handler

---

examples/cli.php
examples/incr.php
examples/publish.php
src/Factory.php
tests/FactoryStreamingClientTest.php

Improve Exception messages for connection issues

---

.gitattributes
.travis.yml
composer.json
phpunit.xml.dist
phpunit.xml.legacy
tests/FactoryStreamingClientTest.php
tests/FunctionalTest.php
tests/LazyClientTest.php

PHPUnit 9.3 released a new schema for the `phpunit.xml` configuration file. I had to migrate the file to the new format in order to avoid the warning. PHPUnit Versions older than 9.3 have to use the `phpunit.xml.legacy` configuration file, because the new format is unknown for them.
For further details concerning this pull request look into https://github.com/graphp/graphviz/pull/46.
This pull request builds on top of [clue/reactphp-redis#101](https://github.com/clue/reactphp-redis/pull/101).
It's also possible to run this code with PHP 8 🎉
```bash
$ docker run -it --rm -v `pwd`:/data --workdir=/data php:8.0.0beta1-cli php vendor/bin/phpunit
PHPUnit 9.3.8 by Sebastian Bergmann and contributors.
.........................................SSSSSSSSSSSSSS........  63 / 104 ( 60%) …
```

Update PHPUnit configuration schema for PHPUnit 9.3

---

src/LazyClient.php
tests/LazyClientTest.php

This is a somewhat hidden and rare race condition. The faulty idle timer
would be started when the underlying Redis connection closes while the
lazy connection still has pending commands, such as a blocking BLPOP
operation. The timer would trigger some timer after the connection has
been closed and would try to close the connection again, thus
referencing undefined variables and causing a hard error in this case.
The idle timer should not be started when the connection is already
closed.

Fix dangling timer when lazy connection closes with pending commands

---

README.md

Use full namespace so the example is runnable

---

README.md
composer.json
examples/cli.php
examples/incr.php
examples/publish.php
examples/subscribe.php
src/Factory.php
tests/FactoryLazyClientTest.php
tests/FactoryStreamingClientTest.php

This changeset simplifies usage by supporting the new [default loop](https://github.com/reactphp/event-loop#loop).
```php
// old (still supported)
$factory = new Clue\React\Redis\Factory($loop);
// new (using default loop)
$factory = new Clue\React\Redis\Factory();
```
Builds on top of reactphp/event-loop#226, reactphp/event-loop#229, reactphp/event-loop#232 and reactphp/socket#260
Closes #110.

Simplify usage by supporting new default loop

---

README.md
composer.json
src/Factory.php

This changeset simplifies usage by supporting the new Socket API without nullable loop arguments.
Note that this doesn't affect the API of this package at all, but does use the improved API of the referenced Socket component. Existing code continues to work as is.
Together with #114, this means we can now fully rely on the [default loop](https://github.com/reactphp/event-loop#loop) and no longer need to skip any arguments with null values.
Builds on top of reactphp/socket#264

Simplify usage by supporting new Socket API

---

README.md
examples/cli.php
examples/incr.php
examples/publish.php
examples/subscribe.php
src/Factory.php
src/LazyClient.php
src/StreamingClient.php
tests/FactoryStreamingClientTest.php
tests/LazyClientTest.php
tests/StreamingClientTest.php

This changeset improves error reporting to include the Redis URI and socket error codes in all connection errors:
```diff
- Error: Connection to Redis server failed because underlying transport connection failed
+ Error: Connection to redis://localhost failed: Connection to localhost:6379 failed: Last error for IPv4: Connection to tcp://127.0.0.1:6379?hostname=localhost failed: Connection refused. Previous error for IPv6: Connection to tcp://[::1]:6379?hostname=localhost failed: Connection refused
```
Builds on top of #89, https://github.com/clue/reactphp-http-proxy/pull/17 and others

Improve error reporting, include Redis URI and socket error codes in all connection errors

---

README.md
examples/cli.php
examples/incr.php
examples/publish.php
examples/subscribe.php
src/Client.php
src/Factory.php
src/LazyClient.php
tests/FactoryLazyClientTest.php
tests/FunctionalTest.php
tests/LazyClientTest.php
tests/StreamingClientTest.php

Builds on top of #116, https://github.com/clue/reactphp-buzz/pull/167 and #112

Improve documentation structure and simplify example code

---

.github/workflows/ci.yml
composer.json
phpunit.xml.dist
src/LazyClient.php

This changeset adds support for PHP 8.1.
~~I'm marking this as WIP because it currently reports a deprecation notice that needs to be addressed upstream first (https://github.com/reactphp/promise-timer/pull/50). I'll update this PR once this version is released.~~
Builds on top of #111
Refs https://github.com/friends-of-reactphp/mysql/pull/150

Support PHP 8.1

---

README.md

The documentation should read `?string $value` instead of `string $value`. Thanks to @fx1234 for pointing this out :+1:
Refs #124
Closes #124

Fix code examples in documentation
